version: "3.4"
services:
  app:
    command: ts-node ./src/server.ts
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes: 
      - .:/app
    environment:
      JWT_SECRET: secret
      MARIADB_PASSWORD: strong
      OMDB_API: b1f19e4c
      NODE_ENV: production